# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order_location', models.TextField()),
                ('order_status', models.TextField()),
                ('order_courier_comment', models.TextField()),
                ('order_client_comment', models.TextField()),
                ('order_client', models.TextField()),
                ('payment_status', models.TextField()),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_cost', models.FloatField()),
                ('order_manager', models.TextField()),
                ('order_courier', models.TextField()),
                ('order_dest_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
